### ISSUE TITLE
NP

### ISSUE THREAD

**Issue by a1binos** [monacoinproject/monacoin#36]
NP

**Comment by wakiyamap** [comment]
I think that monacoin does not have a hash rate corresponding to the current price.
As a countermeasure for the time being, I think that it is nothing other than increasing the number of confirming.

**Comment by cryptcoin-junkey** [comment]
As wakiyamap wrote, it's a simple and effective fix to just increase the number of confirmation.
Some crypto-currency exchanges have already set their confirmation to 30 or 100.

IMO, this issue is caused not by code but by incentive to miners.
Not engineering. But economics, psychology, and some more.
